# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    services:
      postgres:
        image: bitnami/postgresql:12
        env:
          POSTGRESQL_USER: user
          POSTGRESQL_PASSWORD: pass
          POSTGRESQL_DATABASE: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Lint
      run: make lint
    - name: Typecheck
      run: make typecheck
    - name: Test
      run: make test
      env:
        DATABASE_URL: "postgresql://user:pass@postgres/test_db"
